app/models.py
from . import db

class Question(db.Model):
	__tablename__ = 'questions'
	id = db.Column(db.Integer, primary_key=True)
	question = db.Column(db.String, nullable=False)
	answer = db.Column(db.String(20))
	

class Answers(db.Model):
	id = db.Column(db.Integer, primary_key=True)
	a = db.Column(db.String(20), nullable=False)
	b = db.Column(db.String(20), nullable=False)
	c = db.Column(db.String(20), nullable=False)
	d = db.Column(db.String(20), nullable=False)
	q_id = db.Column(db.Integer, db.ForeignKey('questions.id'))

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


# from .main.utils import UsersHandler
def create_app():
    app = Flask(__name__)
    app.secret_key = 'o9rew908qre3qr3$TEw3qejrewqopreREWQr'

    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///questions.db'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    db.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import views

app/main/views.py
from . import main
from flask import render_template, session, redirect, jsonify, url_for, request, session
from .utils import UsersHandler, update_json, QuestionHandler

# users = UsersHandler()


@main.route('/', methods=["GET", "POST"])
def index():
    if request.method == "POST":
        username = request.form.get('namefield', '')
        if username:
            session['username'] = username
            # users.add_user()
            return redirect(url_for('main.questions'))

    username = session.get('username')
    if username:
        return redirect(url_for('main.questions'))
    return render_template('home.html')


@main.route('/quiz', methods=["GET", "POST"])
def questions():
    handler = QuestionHandler()

    if not handler:
        return redirect(url_for('main.index'))

    if request.method == 'POST':
        answer = request.form.get('a')
        correct_answer = handler.question_answer()
        print(answer, correct_answer)
        if answer.lower() == correct_answer.lower():
            print('Good')
            # session['scored'] += 1
        else:
            print('bad')
            # handler.failed += 1

        # handler_object = {}
        # handler_object['question'] = handler.previous_question.question
        # handler_object['options'] = handler.previous_question_options
        # handler_object['correct_answer'] = correct_answer
        # handler_object['picked_answer'] = answer

        # handler.answered_questions.append(handler_object)
        # handler.previous_question_answered = True

    question_answer = handler.get_question()
    if not question_answer:
        return redirect(url_for('main.dashboard'))
    question, answer = question_answer
    total_questions, answered_questions_len = handler.progress_()
    return render_template('quiz.html',
                           qs=question, ans=answer,
                           username=handler.username,
                           q_len=total_questions,
                           ansd_len=answered_questions_len)


@main.route('/quiz/submit', methods=["POST"])
def new_question():
    print(request.json)
    handler = QuestionHandler()
    answer = request.json.get('value')
    correct_answer = handler.question_answer()
    print(answer, correct_answer)
    if answer.lower() == correct_answer.lower():
        handler.save_score(True, fail=False)
        # print('good')
        # handler.score += 1
    else:
        handler.save_score(score=False, fail=True)
        # handler.failed += 1

    # handler_object = {}
    # handler_object['question'] = handler.previous_question.question
    # handler_object['options'] = handler.previous_question_options
    # handler_object['correct_answer'] = correct_answer
    # handler_object['picked_answer'] = answer

    # handler.answered_questions.append(handler_object)
    # handler.previous_question_answered = True
    handler.set_question_answered(correct_answer, answer)
    question_answer = handler.get_question()

    if not question_answer:
        return jsonify({"redirect": True})
    question, answer = question_answer
    total_questions, answered_questions_len = handler.progress_()

    return jsonify({"qs": question, "ans": answer, "q_len": total_questions, "ansd_len": answered_questions_len})


@main.route('/dashboard', methods=["GET", "POST"])
def dashboard():

    if request.method == 'POST':
        # del session['username']
        del session['activities']
        del session['prm']
        quest = request.form.get('quit')

        if not quest:
            # users.reset_user()
            return redirect(url_for('main.questions'))
        else:
            # users.discard_user()
            del session['username']
            return redirect(url_for('main.index'))

    # del session['activities']
    username = session.get('username')
    if not username:
        return redirect(url_for('main.index'))

    handler = QuestionHandler()
    score, failed = handler.get_scores()
    answered_questions = handler.get_answered_q()
    # del session['activities']

    # if not username:
    #     return redirect(url_for('main.index'))

    return render_template('dashboard.html', score=score, failed=failed, questions=answered_questions)


@main.route('/contribute', methods=["GET", "POST"])
def contribute():
    if request.method == 'POST':
        question = request.form.get('question')
        answer = request.form.get('a')
        option_letters = ['b', 'c', 'd']
        options = [request.form.get(i, '') for i in option_letters]
        update_json(question, answer, options)
        options.insert(0, answer)
        return render_template('contribute.html', qs=question, ans=options)

    return render_template('contribute.html')

app/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Yo{% endblock %}</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='css/bootstrap.min.css') }}"
    />
    {% block head %}{% endblock %}
    <style type="text/css">
      body {
        display: flex;
        align-items: center;
      }
      .rounded-3 .answer-button {
        border-radius: 15px !important;
      }
      .rounded-card {
        border-radius: 25px !important;
      }
      .share {
        position: absolute;
        top: 13px;
        right: 3rem;
      }
      .ml1 {
        /* for contribute buttons*/
        margin-left: 10px;
      }
      .mr1 {
        margin-right: 10px;
      }

      #options {
        flex-direction: row;
      }

      @media (max-width: 700px) {
        .logo {
          width: 35%;
          height: 35%;
        }
        #options {
          flex-direction: column;
        }
        .ml1 {
          margin-left: 0;
          margin-top: 10px;
        }
        .mr1 {
          margin-right: 0;
          margin-bottom: 10px;
        }
      }

      /* more */

      .waves {
        position: relative;
        left: 0;
        /* bottom: 0; */
        width: 100%;
        height: 15vh;
        margin-bottom: -7px;
        min-height: 100px;
        max-height: 150px;
      }

      /* Animation */

      .parallax > use {
        animation: move-forever 25s cubic-bezier(0.55, 0.5, 0.45, 0.5) infinite;
      }
      .parallax > use:nth-child(1) {
        animation-delay: -2s;
        animation-duration: 7s;
      }
      .parallax > use:nth-child(2) {
        animation-delay: -3s;
        animation-duration: 10s;
      }
      .parallax > use:nth-child(3) {
        animation-delay: -4s;
        animation-duration: 13s;
      }
      .parallax > use:nth-child(4) {
        animation-delay: -5s;
        animation-duration: 20s;
      }
      @keyframes move-forever {
        0% {
          transform: translate3d(-90px, 0, 0);
        }
        100% {
          transform: translate3d(85px, 0, 0);
        }
      }
      /* waves */
    </style>
  </head>
  <body class="d-flex flex-column" id="entire_body">
    <nav
      class="navbar navbar-expand border-bottom navbar-light w-100"
      style="margin-bottom: 16px; font-size: 16px"
    >
      <div class="container-fluid">
        <a href="#" class="navbar-brand"
          ><img
            class="rounded-pill py-2 bg-body logo shadow-sm"
            src="{{url_for('static', filename='assets/logo.png')}}"
            width="50%"
            height="50%"
        /></a>
        <div class="nav nav-pills">
          <ul class="navbar-nav me-auto">
            {% block nav %}
            <li class="nav-item">
              <a href="{{url_for('main.contribute')}}" class="nav-link">
                Contribute
              </a>
            </li>
            {% endblock nav%}
          </ul>
        </div>
      </div>
    </nav>

    <main class="container bg-body" id="quiz">
      {% block content %} {% endblock %}
    </main>
  </body>

  <script
    type="text/javascript"
    src="{{url_for('static', filename='js/dom-to-image.js')}}"
  ></script>
  <script type="text/javascript">
    const to_image = (d) => {
      //   domtoimage
      //     .toBlob(document.getElementById("#quiz_area"))
      //     .then(function (blob) {
      //       window.saveAs(blob, "image.png");
      //     }
      var scale = 5;
      div = document.getElementById("quiz");
      let id = div;
      domtoimage
        .toPng(div, {
          width: id.clientWidth * scale,
          height: id.clientHeight * scale,
          style: {
            transform: `scale(${scale})`,
            transformOrigin: "top left",
            width: id.clientWidth + "px", // use original width of DOM element to avoid part of the image being cropped out
            height: id.clientHeight + "px", // use original height of DOM element
          },
        })
        .then(function (dataUrl) {
          var link = document.createElement("a");
          link.download = "quix.png";
          link.href = dataUrl;
          link.click();
        });
    };
  </script>
</html>

app/templates/contribute.html
{% extends 'base.html' %}


{% block content %}


{% if not qs %}
<section>
    <form method="post" class="container shadow-lg p-3 rounded-card">
        <div class="d-flex justify-content-between">
            <h2>Contribute</h2>
            <input type="submit" value="submit" class="btn btn-info mb-3"/>
        </div>
        <textarea required type="text" name="question" class="form-control mb-3" placeholder="Question"></textarea>
        <div class="d-flex" id="options">
        <input class="form-control mr1" name="a" required placeholder="Answer"/>
        <input class="form-control mr1" name="b" required placeholder="Option 2"/>
        <input type="button" value="add" class="btn btn-info ml1 w-100" onclick="addOption()"/>
        </div>
    </form>
</section>

<script>
let count = 2;
let names = ['a','b','c','d']
const addOption = () => {
    
    let optionsDiv = document.getElementById('options');
    if (optionsDiv.children.length == 5 ){
        return;
    }
    let elementName = names[count]
    count ++;
    let newElement = document.createElement('input');
    newElement.classList = ['form-control mr1']
    
    newElement.placeholder = `Option ${count}`
    newElement.name = elementName
    

    optionsDiv.insertBefore(newElement, optionsDiv.lastElementChild)
}
</script>


{% else %}

<aside>
<div class=" border-3 shadow-lg rounded-card p-5 w-100 bg-body my-3 position-relative">
	<div class="row">
		<div class="col-lg ">
			<span class="badge p-2 rounded-2 bg-info share text-dark ">
				<a class="text-decoration-none text-dark " target="_" href="https://twitter.com/intent/tweet?text={{qs}}"> Tweet</a>
			</span>
			<p id="question" class="my-0 py-2 mx-0">
				{{ qs }}
			</p>
		</div>

		<div class="col">
			<div class=" d-flex flex-column">
				{% for option in ans %}
				    
					{% if option != ""%}
				<input type="button"  value="{{ option }}" name="a" class='btn rounded-card btn-info mb-3 answer-button'>
					{% endif %}
				{% endfor %}
            </div>

		</div>
	</div>
    <p class="text-center ">Held for review.</p>
</div>

<p class="text-center">You are the best 😍.</p>
</aside>


{% endif %}
{% endblock content %}

app/templates/dashboard.html
{% extends 'base.html' %} {% block title %}Quix{% endblock %} {% block content
%}

<div
  class="container border-3 bg-dark text-white shadow rounded-card w-100 mt-3"
>
  <div class="row text-center">
    <div class="col p-3">
      <p class="display-4 text-success">PASSED</p>
      <p class="display-5">{{score}}</p>
    </div>

    <div class="col p-3">
      <p class="display-4 text-danger">FAILED</p>
      <p class="display-5">{{failed}}</p>
    </div>
  </div>
</div>
<div class="mt-3">
  <input
    onclick="toggle_corrections()"
    class="btn btn-info mb-2"
    type="submit"
    value="toggle answers"
  />
  <form method="POST">
    <input class="btn btn-info" type="submit" value="Play Again" />

    <input class="btn btn-danger" type="submit" name="quit" value="Quit" />
  </form>
</div>

<div class="container mb-3" id="correction_div">
  {% for qs in questions %}
  <div class="border-3 shadow rounded-card p-5 w-100 bg-dark mt-3">
    <div class="row">
      <div class="col-lg text-light">
        <p>{{ qs.question }}</p>
      </div>

      <div class="col">
        <div class="d-flex flex-column" id="answers">
          {% for option in qs.options %} {% if option != "" %} {% if
          option.lower() == qs.correct_answer.lower() %}
          <input
            type="submit"
            value="{{ option }}"
            name="a"
            class="btn btn-success mb-3 rounded-card"
          />

          {% elif option == qs.picked_answer and qs.correct_answer !=
          qs.picked_answer%}

          <input
            type="submit"
            value="{{ option }}"
            name="a"
            class="btn btn-danger mb-3 rounded-card"
          />

          {% else %}
          <input
            type="submit"
            value="{{ option }}"
            name="a"
            class="btn btn-info mb-3 rounded-card"
          />

          {% endif %} {% endif %} {% endfor %}
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

<script type="text/javascript">
  function toggle_corrections() {
    // body..

    let correction_div = document.getElementById("correction_div");

    if (correction_div.style.display == "block") {
      correction_div.style.display = "none";
    } else {
      correction_div.style.display = "block";
    }
  }
  let correction_div = document.getElementById("correction_div");
  correction_div.style.display = "none";
</script>
{% endblock %}

app/templates/home.html
{% extends 'base.html' %}

{% block title %}Quix{% endblock %}
{% block head %}
  <!-- <title>Your Title</title> -->
  <meta property="og:title" content="quix">
  <meta name="twitter:title" content="quix">
  
  <meta name="description" content="Best trivia for game night">
  <meta property="og:description" content="Best trivia for game night">
  <meta name="twitter:description" content="Best trivia for game night">
  
  <meta property="og:image" content="{{url_for('static', filename='assets/med.jpg')}}">
  <meta name="twitter:image" content="{{url_for('static', filename='assets/med.jpg')}}">

{% endblock %}
{% block content %}

<div class="container d-flex flex-column shadow-lg rounded-3 w-100 p-3 mt-5 bg-body">
	<img class="mx-auto" src="{{url_for('static', filename='assets/med.jpg')}}" width="50%" height="50%"/>
	<form method="POST">
		<input type="input" name="namefield" placeholder="Enter a username" class="form-control mb-3" required="true">
		<input type="submit" value="Play ▶" class="btn btn-info w-100 ">
	</form>
</div>

{% endblock %}

app/templates/question.html
{% block content %}

	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
<div class="d-flex flex-column"> 
<div class=" border-3 shadow-lg rounded-3 p-5 w-100 bg-dark my-3 position-relative">
	<div class="row">
		<div class="col-lg text-light ">
			<span class="badge p-2 rounded-2 bg-info share text-dark ">
				<a class="text-decoration-none text-dark " target="_" href="https://twitter.com/intent/tweet?text={{qs}}"> Tweet</a>
			</span>
			<p id="question" class="my-0 py-2 mx-0">
				{{ qs }}
			</p>
		</div>

		<div class="col">
			<form method="POST" class=" d-flex flex-column">
				{% for option in ans %}
				    
					{% if option != ""%}
				<input type="submit"  value="{{ option }}" name="a" class='btn btn-info mb-3 answer-button'>
					{% endif %}
				{% endfor %}
			</form>

		</div>
	</div>

</div>


<div class="container shadow-lg bg-dark m-auto position-relative rounded-3 px-3 d-flex justify-content-between" style="width: 40%;padding-top: 12px;">
	<p class="display-6 text-success">{{ansd_len}}</p>
	<p class="display-6 text-danger">{{q_len}}</p>
</div>

</div>
<script type="text/javascript">
	const tweet_question = () => {
		let text = document.getElementById('question');
		console.log(text.innerText);
	}
</script>
{% endblock %}

app/templates/quiz.html
{% extends 'base.html' %} {% block title %}Quix{% endblock %} {% block nav %}

<li class="nav-item">
  <a href="{{url_for('main.dashboard')}}" class="nav-link btn text-danger"
    >Quit</a
  >
</li>
<li class="nav-item">
  <a href="#" class="nav-link">
    <i class="p-2 rounded-2">{{username}}</i>
  </a>
</li>
<li class="nav-item">
  <input
    type="button"
    class="btn btn-info"
    value="snap"
    onclick="to_image('quiz_area')"
  />
</li>

{% endblock nav%} {% block content %}
<div class="d-flex flex-column mb-3" id="quiz_area">
  <div
    class="border-3 shadow-lg rounded-card p-5 w-100 bg-body my-3 position-relative"
  >
    <div class="row">
      <div class="col-lg text-light">
        <span class="badge p-2 share text-dark">
          <a
            class="text-decoration-none text-dark"
            target="_"
            href="https://twitter.com/intent/tweet?text={{qs}}"
          >
            Tweet</a
          >
        </span>
        <p id="question" class="my-0 py-2 mx-0 text-dark">{{ qs }}</p>
      </div>

      <div class="col">
        <div class="d-flex flex-column" id="button_area">
          {% for option in ans %} {% if option != ""%}
          <input
            type="submit"
            onclick="submit_question('{{ option }}')"
            value="{{ option }}"
            name="a"
            class="btn btn-info mb-3 rounded-card"
          />
          {% endif %} {% endfor %}
        </div>
      </div>
    </div>
  </div>

  <div
    class="container shadow-lg bg-light m-auto position-relative rounded-card px-3 d-flex justify-content-between"
    style="width: 40%; padding-top: 12px"
  >
    <p class="display-6 text-success" id="answered">{{ansd_len}}</p>
    <p class="display-6 text-danger" id="total_question">{{q_len}}</p>
  </div>

  <!-- Waves starts here -->
  <div
    style="
      border-bottom-right-radius: 25px;
      border-bottom-left-radius: 25px;
      overflow: hidden;
    "
  >
    <svg
      class="waves"
      xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink"
      viewBox="0 24 150 28"
      preserveAspectRatio="none"
      shape-rendering="auto"
    >
      <defs>
        <path
          id="gentle-wave"
          d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"
        />
      </defs>
      <g class="parallax">
        <use
          xlink:href="#gentle-wave"
          x="48"
          y="0"
          fill="rgba(49, 210, 242, 0.7)"
        />
        <use
          xlink:href="#gentle-wave"
          x="48"
          y="3"
          fill="rgba(49, 210, 242, 0.5)"
        />
        <use
          xlink:href="#gentle-wave"
          x="48"
          y="5"
          fill="rgba(49, 210, 242, 0.3)"
        />
        <use
          xlink:href="#gentle-wave"
          x="48"
          y="7"
          fill="rgba(49, 210, 242, 0.1)"
        />
      </g>
    </svg>
  </div>
  <!--Waves end-->
</div>
<script
  type="text/javascript"
  src="{{url_for('static', filename='js/handler.js')}}"
></script>
{% endblock %}